name: RN - Github actions for test
on:
  push:
   branches:
    - main
jobs:
  publish:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: yarn
      - run: yarn jest